#!/usr/bin/env Rscript

test_args <- commandArgs(FALSE)
test_file <- sub("^--file=", "", test_args[grepl("^--file=", test_args)])
module_dir <- normalizePath(file.path(dirname(test_file), ".."))
function_file <- file.path(module_dir, "R", "analysis_functions.R")
cli_file <- file.path(module_dir, "scripts", "run_l2p_multi.R")
schema_file <- file.path(module_dir, "schemas", "interface.yml")

stopifnot(file.exists(function_file), file.exists(cli_file), file.exists(schema_file))
invisible(parse(file = function_file))
invisible(parse(file = cli_file))

cli_text <- paste(readLines(cli_file, warn = FALSE), collapse = "\n")
function_text <- paste(readLines(function_file, warn = FALSE), collapse = "\n")
stopifnot(grepl("--deg_table", cli_text, fixed = TRUE))
stopifnot(grepl("--comparisons", cli_text, fixed = TRUE))
stopifnot(grepl("--output_dir", cli_text, fixed = TRUE))
stopifnot(grepl("--pathway_bubble_plots", cli_text, fixed = TRUE))
stopifnot(grepl("--pathway_bubble_top_n", cli_text, fixed = TRUE))
stopifnot(grepl('make_option("--pathway_bubble_top_n", type = "integer", default = 20L,', cli_text, fixed = TRUE))
stopifnot(grepl('make_option("--maximum_pathways_to_plot", type = "integer", default = 20L)', cli_text, fixed = TRUE))
stopifnot(grepl("--pathway_bubble_significance_statistic", cli_text, fixed = TRUE))
stopifnot(grepl('default = "padj"', cli_text, fixed = TRUE))
stopifnot(grepl("--collection_color_scale", cli_text, fixed = TRUE))
stopifnot(grepl("OmixPathwayPlots::plot_pathway_bubble_set", cli_text, fixed = TRUE))
stopifnot(grepl("OmixPathwayPlots::save_pathway_bubble_set", cli_text, fixed = TRUE))
stopifnot(grepl('"across_all_collections"', cli_text, fixed = TRUE))
stopifnot(grepl("selection_contrasts = comparisons", cli_text, fixed = TRUE))
stopifnot(grepl("plot_contrasts = comparisons", cli_text, fixed = TRUE))
stopifnot(grepl("export_plot_file = NULL", cli_text, fixed = TRUE))
stopifnot(grepl('make_option("--select_by_rank", type = "character", default = "false")', cli_text, fixed = TRUE))
stopifnot(grepl("select_by_rank = FALSE", function_text, fixed = TRUE))
stopifnot(!grepl('"/data/', cli_text, fixed = TRUE))
stopifnot(!grepl('"/results"', cli_text, fixed = TRUE))
stopifnot(grepl("if (interactive())", function_text, fixed = TRUE))
stopifnot(grepl("select_l2p_multi_export_pathways", function_text, fixed = TRUE))
stopifnot(!grepl("head(top_pathways)", function_text, fixed = TRUE))

message("OMIX-L2P-Multi module layout checks passed")
