#!/usr/bin/env Rscript

test_args <- commandArgs(FALSE)
test_file <- sub("^--file=", "", test_args[grepl("^--file=", test_args)])
module_dir <- normalizePath(file.path(dirname(test_file), ".."))
function_file <- file.path(module_dir, "R", "L2P_Analysis.R")
cli_file <- file.path(module_dir, "scripts", "run_l2p_single.R")
schema_file <- file.path(module_dir, "schemas", "interface.yml")

stopifnot(file.exists(function_file), file.exists(cli_file), file.exists(schema_file))
invisible(parse(file = function_file))
invisible(parse(file = cli_file))

cli_text <- paste(readLines(cli_file, warn = FALSE), collapse = "\n")
function_text <- paste(readLines(function_file, warn = FALSE), collapse = "\n")
stopifnot(grepl("--deg_table", cli_text, fixed = TRUE))
stopifnot(grepl("--comparison", cli_text, fixed = TRUE))
stopifnot(grepl("--comparisons", cli_text, fixed = TRUE))
stopifnot(grepl('opt[["comparison"]]', cli_text, fixed = TRUE))
stopifnot(grepl('opt[["comparisons"]]', cli_text, fixed = TRUE))
stopifnot(grepl("Supply either `--comparison` or `--comparisons`, not both", cli_text, fixed = TRUE))
stopifnot(grepl("--output_dir", cli_text, fixed = TRUE))
stopifnot(grepl('make_option("--number_of_pathways_to_plot", type = "integer", default = 20L)', cli_text, fixed = TRUE))
stopifnot(grepl('make_option("--select_by_rank", type = "character", default = "false")', cli_text, fixed = TRUE))
stopifnot(grepl("select_by_rank = FALSE", function_text, fixed = TRUE))
stopifnot(grepl("number_of_pathways_to_plot = 20", function_text, fixed = TRUE))
stopifnot(grepl("plot_title_prefix = NULL", function_text, fixed = TRUE))
stopifnot(grepl("l2p_result$direction <- plot_directions[[i]]", function_text, fixed = TRUE))
stopifnot(grepl("l2p_single_run_manifest.csv", cli_text, fixed = TRUE))
stopifnot(!grepl('"/data/', cli_text, fixed = TRUE))
stopifnot(!grepl('"/results"', cli_text, fixed = TRUE))
stopifnot(grepl("if (interactive())", function_text, fixed = TRUE))
stopifnot(grepl("message(wrapped_message)", function_text, fixed = TRUE))

message("OMIX-L2P-Single module layout checks passed")
